import type { NextPage } from 'next';
import Head from 'next/head';

import Layout from '@/theme/Layout';
import { useEffect } from 'react';
import Card from '@/components/Card';

import { getPlaces } from '@/services/place';

const Home: NextPage = () => {
    useEffect(() => {
        (async () => {
            try {
                const res = await getPlaces();
                console.log('res', res);
                if (res.status === 200 && res.statusText === 'OK') {
                }
            } catch (error) {}
        })();
    }, []);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <Card />
            </Layout>
        </div>
    );
};

export default Home;
