import type { NextPage } from 'next';
import Head from 'next/head';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSearch } from '@fortawesome/free-solid-svg-icons';

import Layout from '@/Layout';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <h1 className="text-5xl">
                    Welcome o <a href="https://nextjs.org">Next.js!</a>
                </h1>
            </Layout>
        </div>
    );
};

export default Home;
